import asyncio
from typing import Any, Dict, Optional, Tuple

from app.core.logger import logger


class TtsPipeline:
    """
    TTS pipeline with parallel prefetch.

    Two-worker architecture:
    - _prefetch_worker: dequeues text tasks and immediately fires a background
      TTS generation task (asyncio.create_task) so audio is being generated
      while the previous chunk is still playing.
    - _playback_worker: awaits each prefetch future in order and calls
      _stream_tts_chunk with the pre-generated bytes, eliminating the
      inter-chunk TTS API latency gap (~200–400 ms per sentence boundary).

    Backward-compat: _worker_task property returns _playback_worker_task so
    callers that stored a reference to the old single-worker task (e.g.
    VoiceOrchestrator) continue to work without modification.
    """

    def __init__(self, handler: Any) -> None:
        self._handler = handler
        # Incoming text tasks from queue_tts()
        self._incoming: "asyncio.Queue[Optional[Dict[str, Any]]]" = asyncio.Queue()
        # (task, prefetch_future) pairs forwarded in playback order
        self._prefetch_ready: "asyncio.Queue[Optional[Tuple[Dict[str, Any], asyncio.Task]]]" = asyncio.Queue()
        # Track in-flight generation tasks so we can cancel them on barge-in
        self._active_prefetch_tasks: set = set()
        self._prefetch_worker_task: Optional[asyncio.Task] = asyncio.create_task(
            self._prefetch_worker()
        )
        self._playback_worker_task: Optional[asyncio.Task] = asyncio.create_task(
            self._playback_worker()
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def _worker_task(self) -> Optional[asyncio.Task]:
        """Backward-compatible alias used by VoiceOrchestrator."""
        return self._playback_worker_task

    @property
    def cancel_event(self) -> asyncio.Event:
        return self._handler._tts_cancel  # type: ignore[attr-defined]

    @property
    def is_speaking(self) -> bool:
        return bool(getattr(self._handler, "is_speaking", False))

    async def queue_tts(self, task: Dict[str, Any]) -> None:
        """
        Enqueue a TTS task. Fields:
        - text (str)
        - use_ssml (bool)
        - is_final (bool)
        - end_call_after (bool, optional)
        """
        await self._incoming.put(task)

    async def cancel_current_and_clear_queue(self) -> None:
        """
        Barge-in: stop current playback, cancel all in-flight prefetch
        generation tasks, and drain both internal queues.
        """
        if not self.cancel_event.is_set():
            self.cancel_event.set()

        # Cancel every background generation task immediately
        for t in list(self._active_prefetch_tasks):
            t.cancel()
        self._active_prefetch_tasks.clear()

        # Drain incoming queue
        try:
            while not self._incoming.empty():
                self._incoming.get_nowait()
                self._incoming.task_done()
        except (asyncio.QueueEmpty, ValueError):
            pass

        # Drain prefetch-ready queue; cancel any generation futures still queued
        try:
            while not self._prefetch_ready.empty():
                item = self._prefetch_ready.get_nowait()
                self._prefetch_ready.task_done()
                if item is not None:
                    _, fut = item
                    fut.cancel()
        except (asyncio.QueueEmpty, ValueError):
            pass

        if hasattr(self._handler, "is_speaking"):
            self._handler.is_speaking = False
        if hasattr(self._handler, "_twilio_buffer_primed"):
            self._handler._twilio_buffer_primed = False
        if hasattr(self._handler, "_prev_tts_tail"):
            self._handler._prev_tts_tail = b""

    async def shutdown(self) -> None:
        """
        Gracefully stop both workers and every in-flight prefetch task.

        The three categories of tasks we must drain:
        1. _prefetch_worker_task / _playback_worker_task — the two long-running
           worker loops.
        2. _active_prefetch_tasks — individual asyncio.Tasks for each
           _prefetch_tts_audio() call that is currently running a TTS API
           request.  These are the root cause of "Task was destroyed but it is
           pending" warnings under load: shutdown() previously cancelled only
           the worker loops, leaving the generation tasks alive and orphaned.

        Strategy:
        - Send a None sentinel so _prefetch_worker can exit cleanly via its
          normal loop path (avoids a spurious CancelledError log entry).
        - Cancel every task in all three categories.
        - gather() everything with return_exceptions=True so we wait until
          every task has reached a terminal state before returning.
        """
        # Sentinel: lets the prefetch worker exit via its normal break path
        try:
            self._incoming.put_nowait(None)
        except Exception:
            pass

        # Snapshot the generation tasks before cancelling (the done-callback
        # removes finished tasks from the set, so iterate a copy).
        generation_tasks = list(self._active_prefetch_tasks)

        # Build the full set of tasks that must reach Done/Cancelled
        all_tasks = [
            t for t in (
                *generation_tasks,
                self._prefetch_worker_task,
                self._playback_worker_task,
            )
            if t is not None and not t.done()
        ]

        for t in all_tasks:
            t.cancel()

        if all_tasks:
            await asyncio.gather(*all_tasks, return_exceptions=True)

        self._active_prefetch_tasks.clear()

    # ------------------------------------------------------------------
    # Internal workers
    # ------------------------------------------------------------------

    async def _prefetch_worker(self) -> None:
        """
        Stage 1: pull tasks as fast as they arrive and immediately kick off
        TTS audio generation as a background asyncio.Task.  The task runs
        concurrently while the playback worker is busy streaming the previous
        chunk to Twilio — so by the time playback is ready for the next chunk,
        its audio is already buffered (or nearly so).
        """
        try:
            while True:
                task = await self._incoming.get()

                if task is None:
                    # Propagate shutdown sentinel to playback worker and exit
                    try:
                        self._prefetch_ready.put_nowait(None)
                    except Exception:
                        pass
                    self._incoming.task_done()
                    break

                if self.cancel_event.is_set():
                    self._incoming.task_done()
                    continue

                text = task.get("text", "")
                if not text or not text.strip():
                    self._incoming.task_done()
                    continue

                # Fire TTS generation immediately — runs in event-loop background
                # while the playback worker is still busy with the previous chunk.
                prefetch_task: asyncio.Task = asyncio.create_task(
                    self._handler._prefetch_tts_audio(task)  # type: ignore[attr-defined]
                )
                self._active_prefetch_tasks.add(prefetch_task)
                prefetch_task.add_done_callback(self._active_prefetch_tasks.discard)

                await self._prefetch_ready.put((task, prefetch_task))
                self._incoming.task_done()

        except asyncio.CancelledError:
            pass  # Cancelled by shutdown() — exit cleanly
        except Exception as exc:
            logger.error("[TTS] prefetch worker error: %s", exc, exc_info=True)

    async def _playback_worker(self) -> None:
        """
        Stage 2: consume (task, prefetch_future) pairs in order.
        Awaiting the future returns instantly when generation already finished
        during the previous chunk's playback — eliminating inter-chunk gaps.
        """
        try:
            while True:
                item = await self._prefetch_ready.get()

                if item is None:
                    try:
                        self._prefetch_ready.task_done()
                    except ValueError:
                        pass
                    break

                task, prefetch_task = item

                try:
                    if self.cancel_event.is_set():
                        prefetch_task.cancel()
                        continue

                    text = task.get("text", "")
                    use_ssml = task.get("use_ssml", False)
                    is_final = task.get("is_final", False)
                    end_call_after = task.get("end_call_after", False)

                    if not text or not text.strip():
                        prefetch_task.cancel()
                        continue

                    # Await pre-generated audio (typically already done)
                    try:
                        audio_bytes: Optional[bytes] = await prefetch_task
                    except asyncio.CancelledError:
                        audio_bytes = None
                    except Exception as exc:
                        logger.warning("[TTS] prefetch task failed: %s", exc)
                        audio_bytes = None

                    if self.cancel_event.is_set():
                        continue

                    # Delegate to handler for crossfade + Twilio streaming
                    await self._handler._stream_tts_chunk(  # type: ignore[attr-defined]
                        text,
                        use_ssml=use_ssml,
                        is_final=is_final,
                        prefetched_bytes=audio_bytes,
                    )

                    if end_call_after and hasattr(self._handler, "_end_call_after_agent_request"):
                        await self._handler._end_call_after_agent_request()

                except asyncio.CancelledError:
                    raise  # Let the outer CancelledError handler catch this
                except Exception as exc:
                    logger.error("[TTS] playback worker loop error: %s", exc, exc_info=True)
                finally:
                    try:
                        self._prefetch_ready.task_done()
                    except ValueError:
                        pass  # task_done() on already-drained queue during barge-in

        except asyncio.CancelledError:
            pass  # Cancelled by shutdown() — exit cleanly
        except Exception as exc:
            logger.error("[TTS] playback worker fatal: %s", exc, exc_info=True)
