import asyncio
from typing import Any, Dict, Optional, Tuple

from app.core.logger import logger


class TtsPipeline:
    """
    TTS pipeline with parallel prefetch.

    Two-worker architecture:
    - _prefetch_worker: dequeues text tasks and immediately fires a background
      TTS generation task (asyncio.create_task) so audio is being generated
      while the previous chunk is still playing.
    - _playback_worker: awaits each prefetch future in order and calls
      _stream_tts_chunk with the pre-generated bytes, eliminating the
      inter-chunk TTS API latency gap (~200–400 ms per sentence boundary).

    Barge-in / cancel: cancel_current_and_clear_queue cancels all in-flight
    prefetch tasks and drains both internal queues, then resets handler state
    exactly as before.
    """

    def __init__(self, handler: Any) -> None:
        self._handler = handler
        # Incoming text tasks from queue_tts()
        self._incoming: "asyncio.Queue[Optional[Dict[str, Any]]]" = asyncio.Queue()
        # (task, prefetch_future) pairs in playback order
        self._prefetch_ready: "asyncio.Queue[Optional[Tuple[Dict[str, Any], asyncio.Task]]]" = asyncio.Queue()
        # Track in-flight generation tasks so we can cancel them on barge-in
        self._active_prefetch_tasks: set = set()
        self._prefetch_worker_task: Optional[asyncio.Task] = asyncio.create_task(
            self._prefetch_worker()
        )
        self._playback_worker_task: Optional[asyncio.Task] = asyncio.create_task(
            self._playback_worker()
        )

    # ------------------------------------------------------------------
    # Public API (unchanged from original)
    # ------------------------------------------------------------------

    @property
    def cancel_event(self) -> asyncio.Event:
        return self._handler._tts_cancel  # type: ignore[attr-defined]

    @property
    def is_speaking(self) -> bool:
        return bool(getattr(self._handler, "is_speaking", False))

    async def queue_tts(self, task: Dict[str, Any]) -> None:
        """
        Enqueue a TTS task. Fields:
        - text (str)
        - use_ssml (bool)
        - is_final (bool)
        - end_call_after (bool, optional)
        """
        await self._incoming.put(task)

    async def cancel_current_and_clear_queue(self) -> None:
        """
        Barge-in: stop current playback, cancel all in-flight prefetch
        generation tasks, and drain both internal queues.
        """
        if not self.cancel_event.is_set():
            self.cancel_event.set()

        # Cancel every background generation task immediately
        for t in list(self._active_prefetch_tasks):
            t.cancel()
        self._active_prefetch_tasks.clear()

        # Drain incoming queue
        try:
            while not self._incoming.empty():
                self._incoming.get_nowait()
                self._incoming.task_done()
        except (asyncio.QueueEmpty, ValueError):
            pass

        # Drain prefetch-ready queue (also cancel any futures still inside)
        try:
            while not self._prefetch_ready.empty():
                item = self._prefetch_ready.get_nowait()
                self._prefetch_ready.task_done()
                if item is not None:
                    _, fut = item
                    fut.cancel()
        except (asyncio.QueueEmpty, ValueError):
            pass

        if hasattr(self._handler, "is_speaking"):
            self._handler.is_speaking = False
        if hasattr(self._handler, "_twilio_buffer_primed"):
            self._handler._twilio_buffer_primed = False
        if hasattr(self._handler, "_prev_tts_tail"):
            self._handler._prev_tts_tail = b""

    async def shutdown(self) -> None:
        """Gracefully stop both workers."""
        try:
            await self._incoming.put(None)
            if self._prefetch_worker_task:
                await asyncio.wait_for(self._prefetch_worker_task, timeout=2.0)
        except (asyncio.TimeoutError, Exception):
            pass
        try:
            if self._playback_worker_task:
                await asyncio.wait_for(self._playback_worker_task, timeout=2.0)
        except (asyncio.TimeoutError, Exception):
            pass

    # ------------------------------------------------------------------
    # Internal workers
    # ------------------------------------------------------------------

    async def _prefetch_worker(self) -> None:
        """
        Stage 1: pull tasks as fast as they arrive and immediately kick off
        TTS audio generation as a background asyncio.Task.  The task runs
        concurrently while the playback worker is busy streaming the previous
        chunk to Twilio — so by the time playback is ready for the next chunk,
        its audio is already buffered (or nearly so).
        """
        try:
            while True:
                task = await self._incoming.get()

                if task is None:
                    # Propagate shutdown sentinel to playback worker
                    await self._prefetch_ready.put(None)
                    self._incoming.task_done()
                    break

                if self.cancel_event.is_set():
                    self._incoming.task_done()
                    continue

                text = task.get("text", "")
                if not text or not text.strip():
                    self._incoming.task_done()
                    continue

                # Fire generation immediately — runs in event-loop background
                prefetch_task: asyncio.Task = asyncio.create_task(
                    self._handler._prefetch_tts_audio(task)  # type: ignore[attr-defined]
                )
                self._active_prefetch_tasks.add(prefetch_task)
                prefetch_task.add_done_callback(self._active_prefetch_tasks.discard)

                await self._prefetch_ready.put((task, prefetch_task))
                self._incoming.task_done()

        except Exception as exc:
            logger.error("[TTS] prefetch worker error: %s", exc, exc_info=True)

    async def _playback_worker(self) -> None:
        """
        Stage 2: consume (task, prefetch_future) pairs in order.
        Awaiting the future returns instantly when generation already finished
        during the previous chunk's playback — eliminating inter-chunk gaps.
        """
        try:
            while True:
                item = await self._prefetch_ready.get()

                if item is None:
                    self._prefetch_ready.task_done()
                    break

                task, prefetch_task = item

                try:
                    if self.cancel_event.is_set():
                        prefetch_task.cancel()
                        continue

                    text = task.get("text", "")
                    use_ssml = task.get("use_ssml", False)
                    is_final = task.get("is_final", False)
                    end_call_after = task.get("end_call_after", False)

                    if not text or not text.strip():
                        prefetch_task.cancel()
                        continue

                    # Await pre-generated audio (usually already done)
                    try:
                        audio_bytes: Optional[bytes] = await prefetch_task
                    except asyncio.CancelledError:
                        audio_bytes = None
                    except Exception as exc:
                        logger.warning("[TTS] prefetch task failed: %s", exc)
                        audio_bytes = None

                    if self.cancel_event.is_set():
                        continue

                    # Delegate playback (with pre-generated bytes when available)
                    await self._handler._stream_tts_chunk(  # type: ignore[attr-defined]
                        text,
                        use_ssml=use_ssml,
                        is_final=is_final,
                        prefetched_bytes=audio_bytes,
                    )

                    if end_call_after and hasattr(self._handler, "_end_call_after_agent_request"):
                        await self._handler._end_call_after_agent_request()

                except Exception as exc:
                    logger.error("[TTS] playback worker loop error: %s", exc, exc_info=True)
                finally:
                    self._prefetch_ready.task_done()

        except Exception as exc:
            logger.error("[TTS] playback worker fatal: %s", exc, exc_info=True)
