"""Fixing missing tables

Revision ID: 537f4295714b
Revises: 20260429_user_products_link
Create Date: 2026-05-04 15:33:01.180758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '537f4295714b'
down_revision: Union[str, Sequence[str], None] = '20260429_user_products_link'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('crm_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_crm_type'), 'plan', ['crm_type'], unique=False)
    op.create_index(op.f('ix_plan_id'), 'plan', ['id'], unique=False)
    op.create_index(op.f('ix_plan_name'), 'plan', ['name'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    op.create_table('provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.create_index(op.f('ix_provider_name'), 'provider', ['name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('credits', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tenant_stripe_customer_id'), 'tenant', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_tenant_stripe_subscription_id'), 'tenant', ['stripe_subscription_id'], unique=False)
    op.create_table('ttsprovider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('supports_ssml', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ttsprovider_id'), 'ttsprovider', ['id'], unique=False)
    op.create_index(op.f('ix_ttsprovider_slug'), 'ttsprovider', ['slug'], unique=True)
    op.create_table('blockedslot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('blocked_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockedslot_id'), 'blockedslot', ['id'], unique=False)
    op.create_index(op.f('ix_blockedslot_tenant_id'), 'blockedslot', ['tenant_id'], unique=False)
    op.create_table('businesshours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('timezone', sa.String(length=60), server_default='UTC', nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'day_of_week', name='uq_businesshours_tenant_day')
    )
    op.create_index(op.f('ix_businesshours_id'), 'businesshours', ['id'], unique=False)
    op.create_index(op.f('ix_businesshours_tenant_id'), 'businesshours', ['tenant_id'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.String(length=1000), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.Column('llm_cost_per_minute', sa.Float(), nullable=True),
    sa.Column('twilio_cost_per_minute', sa.Float(), nullable=True),
    sa.Column('total_cost_per_minute', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_table('ttsvoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('external_voice_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('accent', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preview_audio_url', sa.String(length=1000), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ttsprovider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_voice_id', name='uq_ttsvoice_provider_external')
    )
    op.create_index(op.f('ix_ttsvoice_id'), 'ttsvoice', ['id'], unique=False)
    op.create_index(op.f('ix_ttsvoice_is_active'), 'ttsvoice', ['is_active'], unique=False)
    op.create_index(op.f('ix_ttsvoice_language_code'), 'ttsvoice', ['language_code'], unique=False)
    op.create_index(op.f('ix_ttsvoice_provider_id'), 'ttsvoice', ['provider_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('join_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('provider_profile', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_provider'), 'user', ['provider'], unique=False)
    op.create_index(op.f('ix_user_provider_user_id'), 'user', ['provider_user_id'], unique=False)
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('voice_type', sa.String(length=100), nullable=True),
    sa.Column('fallback_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('provider_agent_id', sa.String(length=255), nullable=True),
    sa.Column('tts_provider_id', sa.UUID(), nullable=True),
    sa.Column('tts_voice_id', sa.UUID(), nullable=True),
    sa.Column('tts_settings_json', sa.JSON(), nullable=True),
    sa.Column('agent_temperature', sa.Integer(), nullable=True),
    sa.Column('agent_max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_inbound_agent', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tts_provider_id'], ['ttsprovider.id'], ),
    sa.ForeignKeyConstraint(['tts_voice_id'], ['ttsvoice.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_index('uq_agent_single_inbound_per_tenant', 'agent', ['tenant_id'], unique=True, postgresql_where=sa.text('is_inbound_agent = true AND is_deleted = false'))
    op.create_table('crmconfig',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crm_type', sa.String(length=20), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=1000), nullable=False),
    sa.Column('container_id', sa.String(length=200), nullable=True),
    sa.Column('container_url', sa.String(length=500), nullable=True),
    sa.Column('additional_config', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crmconfig_container_id'), 'crmconfig', ['container_id'], unique=False)
    op.create_index(op.f('ix_crmconfig_crm_type'), 'crmconfig', ['crm_type'], unique=True)
    op.create_index(op.f('ix_crmconfig_id'), 'crmconfig', ['id'], unique=False)
    op.create_table('invite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_email'), 'invite', ['email'], unique=False)
    op.create_index(op.f('ix_invite_id'), 'invite', ['id'], unique=False)
    op.create_index(op.f('ix_invite_token'), 'invite', ['token'], unique=True)
    op.create_table('jobdescription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('years_experience_min', sa.Integer(), nullable=True),
    sa.Column('years_experience_max', sa.Integer(), nullable=True),
    sa.Column('education_requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=12), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('key_responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pass_match_threshold', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_weight_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matching_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobdescription_id'), 'jobdescription', ['id'], unique=False)
    op.create_index(op.f('ix_jobdescription_tenant_id'), 'jobdescription', ['tenant_id'], unique=False)
    op.create_table('passwordresettoken',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresettoken_expires_at'), 'passwordresettoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_passwordresettoken_id'), 'passwordresettoken', ['id'], unique=False)
    op.create_index(op.f('ix_passwordresettoken_token'), 'passwordresettoken', ['token'], unique=True)
    op.create_index(op.f('ix_passwordresettoken_user_id'), 'passwordresettoken', ['user_id'], unique=False)
    op.create_table('refreshtoken',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('replaced_by_token', sa.String(length=255), nullable=True),
    sa.Column('replaced_access_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_expires_at'), 'refreshtoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refreshtoken_id'), 'refreshtoken', ['id'], unique=False)
    op.create_index(op.f('ix_refreshtoken_token'), 'refreshtoken', ['token'], unique=True)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('crm_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'crm_type', name='uq_user_crm_subscription')
    )
    op.create_index(op.f('ix_subscription_crm_type'), 'subscription', ['crm_type'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_customer_id'), 'subscription', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_session_id'), 'subscription', ['stripe_session_id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_subscription_id'), 'subscription', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('tenantinboundcrmconfig',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), server_default='trello', nullable=False),
    sa.Column('connection_type', sa.String(length=30), server_default='byo_credentials', nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_api_token', sa.Text(), nullable=True),
    sa.Column('container_id', sa.String(length=200), nullable=True),
    sa.Column('container_url', sa.String(length=500), nullable=True),
    sa.Column('default_list_id', sa.String(length=200), nullable=True),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenantinboundcrmconfig_container_id'), 'tenantinboundcrmconfig', ['container_id'], unique=False)
    op.create_index(op.f('ix_tenantinboundcrmconfig_id'), 'tenantinboundcrmconfig', ['id'], unique=False)
    op.create_index(op.f('ix_tenantinboundcrmconfig_tenant_id'), 'tenantinboundcrmconfig', ['tenant_id'], unique=True)
    op.create_table('user_tenant_association',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('callsession',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.String(length=20), server_default='inbound', nullable=False),
    sa.Column('success_evaluation', sa.String(length=20), nullable=True),
    sa.Column('ended_reason', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('cost_currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('call_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=255), nullable=True),
    sa.Column('from_number', sa.String(length=50), nullable=True),
    sa.Column('to_number', sa.String(length=50), nullable=True),
    sa.Column('assistant_phone_number', sa.String(length=50), nullable=True),
    sa.Column('customer_phone_number', sa.String(length=50), nullable=True),
    sa.Column('call_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callsession_id'), 'callsession', ['id'], unique=False)
    op.create_index(op.f('ix_callsession_twilio_call_sid'), 'callsession', ['twilio_call_sid'], unique=False)
    op.create_table('knowledgebasedocument',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=120), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebasedocument_agent_id'), 'knowledgebasedocument', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledgebasedocument_id'), 'knowledgebasedocument', ['id'], unique=False)
    op.create_index(op.f('ix_knowledgebasedocument_tenant_id'), 'knowledgebasedocument', ['tenant_id'], unique=False)
    op.create_table('phonenumber',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('twilio_phone_number_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_account_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_auth_token', sa.String(length=500), nullable=True),
    sa.Column('assistant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_phone_number_global')
    )
    op.create_index(op.f('ix_phonenumber_id'), 'phonenumber', ['id'], unique=False)
    op.create_index(op.f('ix_phonenumber_phone_number'), 'phonenumber', ['phone_number'], unique=False)
    op.create_index(op.f('ix_phonenumber_tenant_id'), 'phonenumber', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_phonenumber_twilio_phone_number_sid'), 'phonenumber', ['twilio_phone_number_sid'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='parsestatus'), nullable=False),
    sa.Column('upload_mode', sa.Enum('SINGLE', 'BATCH', name='uploadmode'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('overall_match_score', sa.Float(), nullable=True),
    sa.Column('match_percent', sa.Integer(), nullable=True),
    sa.Column('fit_label', sa.String(length=32), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('candidate_status', sa.Enum('QUALIFIED', 'PARTIALLY_QUALIFIED', 'REJECTED', name='candidatestatus'), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('parse_source', sa.String(length=32), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['jobdescription.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_batch_id'), 'resume', ['batch_id'], unique=False)
    op.create_index(op.f('ix_resume_candidate_status'), 'resume', ['candidate_status'], unique=False)
    op.create_index(op.f('ix_resume_id'), 'resume', ['id'], unique=False)
    op.create_index(op.f('ix_resume_job_description_id'), 'resume', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resume_status'), 'resume', ['status'], unique=False)
    op.create_index(op.f('ix_resume_tenant_id'), 'resume', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_resume_upload_mode'), 'resume', ['upload_mode'], unique=False)
    op.create_table('usagerecord',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('agents_created', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usagerecord_id'), 'usagerecord', ['id'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('call_session_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('appointment_reason', sa.Text(), nullable=True),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_via', sa.String(length=20), server_default='web', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('customer_notified_on_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_agent_id'), 'appointment', ['agent_id'], unique=False)
    op.create_index(op.f('ix_appointment_id'), 'appointment', ['id'], unique=False)
    op.create_index(op.f('ix_appointment_slot_start'), 'appointment', ['slot_start'], unique=False)
    op.create_index(op.f('ix_appointment_tenant_id'), 'appointment', ['tenant_id'], unique=False)
    op.create_index('uq_appointment_tenant_slot_active', 'appointment', ['tenant_id', 'slot_start'], unique=True, postgresql_where=sa.text("status != 'cancelled'"), sqlite_where=sa.text("status != 'cancelled'"))
    op.create_table('calllog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=False),
    sa.Column('external_call_id', sa.String(length=255), nullable=True),
    sa.Column('call_type', sa.String(length=20), server_default='inbound', nullable=False),
    sa.Column('success_evaluation', sa.String(length=20), nullable=True),
    sa.Column('ended_reason', sa.String(length=255), nullable=True),
    sa.Column('transferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assistant_phone_number', sa.String(length=50), nullable=True),
    sa.Column('customer_phone_number', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('cost_currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('call_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calllog_call_id'), 'calllog', ['call_id'], unique=False)
    op.create_index(op.f('ix_calllog_call_session_id'), 'calllog', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_calllog_external_call_id'), 'calllog', ['external_call_id'], unique=False)
    op.create_index(op.f('ix_calllog_id'), 'calllog', ['id'], unique=False)
    op.create_index(op.f('ix_calllog_tenant_id'), 'calllog', ['tenant_id'], unique=False)
    op.create_table('knowledgebasechunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=300), nullable=False),
    sa.Column('text_preview', sa.String(length=700), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledgebasedocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebasechunk_chunk_index'), 'knowledgebasechunk', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_knowledgebasechunk_document_id'), 'knowledgebasechunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledgebasechunk_id'), 'knowledgebasechunk', ['id'], unique=False)
    op.create_index(op.f('ix_knowledgebasechunk_vector_id'), 'knowledgebasechunk', ['vector_id'], unique=True)
    op.create_table('resumeinterview',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=True),
    sa.Column('candidate_phone', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), server_default='SCHEDULE_REQUESTED', nullable=False),
    sa.Column('crm_type', sa.String(length=20), nullable=True),
    sa.Column('crm_item_id', sa.String(length=128), nullable=True),
    sa.Column('crm_batch_id', sa.String(length=128), nullable=True),
    sa.Column('phone_number_id', sa.UUID(), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_description_id'], ['jobdescription.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phonenumber.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumeinterview_agent_id'), 'resumeinterview', ['agent_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_call_session_id'), 'resumeinterview', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_crm_batch_id'), 'resumeinterview', ['crm_batch_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_crm_item_id'), 'resumeinterview', ['crm_item_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_id'), 'resumeinterview', ['id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_job_description_id'), 'resumeinterview', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_resume_id'), 'resumeinterview', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_status'), 'resumeinterview', ['status'], unique=False)
    op.create_index(op.f('ix_resumeinterview_tenant_id'), 'resumeinterview', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_twilio_call_sid'), 'resumeinterview', ['twilio_call_sid'], unique=False)
    op.create_table('slotreservation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slotreservation_agent_id'), 'slotreservation', ['agent_id'], unique=False)
    op.create_index(op.f('ix_slotreservation_call_session_id'), 'slotreservation', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_slotreservation_id'), 'slotreservation', ['id'], unique=False)
    op.create_index(op.f('ix_slotreservation_slot_start'), 'slotreservation', ['slot_start'], unique=False)
    op.create_index(op.f('ix_slotreservation_status'), 'slotreservation', ['status'], unique=False)
    op.create_index('ix_slotreservation_tenant_active_time', 'slotreservation', ['tenant_id', 'status', 'slot_start'], unique=False)
    op.create_index(op.f('ix_slotreservation_tenant_id'), 'slotreservation', ['tenant_id'], unique=False)
    op.create_table('transcriptmessage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptmessage_agent_id'), 'transcriptmessage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_transcriptmessage_call_session_id'), 'transcriptmessage', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_transcriptmessage_id'), 'transcriptmessage', ['id'], unique=False)
    op.create_index(op.f('ix_transcriptmessage_user_id'), 'transcriptmessage', ['user_id'], unique=False)
    op.create_table('calllogcrmsync',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_log_id', sa.UUID(), nullable=False),
    sa.Column('tenant_inbound_crm_config_id', sa.UUID(), nullable=False),
    sa.Column('external_item_id', sa.String(length=200), nullable=True),
    sa.Column('external_item_url', sa.String(length=800), nullable=True),
    sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_log_id'], ['calllog.id'], ),
    sa.ForeignKeyConstraint(['tenant_inbound_crm_config_id'], ['tenantinboundcrmconfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calllogcrmsync_call_log_id'), 'calllogcrmsync', ['call_log_id'], unique=True)
    op.create_index(op.f('ix_calllogcrmsync_external_item_id'), 'calllogcrmsync', ['external_item_id'], unique=False)
    op.create_index(op.f('ix_calllogcrmsync_id'), 'calllogcrmsync', ['id'], unique=False)
    op.create_index(op.f('ix_calllogcrmsync_tenant_inbound_crm_config_id'), 'calllogcrmsync', ['tenant_inbound_crm_config_id'], unique=False)
    op.create_table('scheduledcall',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_crm_config_id', sa.UUID(), nullable=True),
    sa.Column('crm_container_id', sa.String(length=200), nullable=True),
    sa.Column('crm_container_url', sa.String(length=500), nullable=True),
    sa.Column('crm_type', sa.String(length=20), nullable=True),
    sa.Column('monday_board_id', sa.String(length=50), nullable=True),
    sa.Column('monday_board_url', sa.String(length=500), nullable=True),
    sa.Column('resume_interview_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_interview_id'], ['resumeinterview.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduledcall_crm_container_id'), 'scheduledcall', ['crm_container_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_crm_type'), 'scheduledcall', ['crm_type'], unique=False)
    op.create_index(op.f('ix_scheduledcall_id'), 'scheduledcall', ['id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_monday_board_id'), 'scheduledcall', ['monday_board_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_resume_interview_id'), 'scheduledcall', ['resume_interview_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_tenant_crm_config_id'), 'scheduledcall', ['tenant_crm_config_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_user_id'), 'scheduledcall', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduledcall_user_id'), table_name='scheduledcall')
    op.drop_index(op.f('ix_scheduledcall_tenant_crm_config_id'), table_name='scheduledcall')
    op.drop_index(op.f('ix_scheduledcall_resume_interview_id'), table_name='scheduledcall')
    op.drop_index(op.f('ix_scheduledcall_monday_board_id'), table_name='scheduledcall')
    op.drop_index(op.f('ix_scheduledcall_id'), table_name='scheduledcall')
    op.drop_index(op.f('ix_scheduledcall_crm_type'), table_name='scheduledcall')
    op.drop_index(op.f('ix_scheduledcall_crm_container_id'), table_name='scheduledcall')
    op.drop_table('scheduledcall')
    op.drop_index(op.f('ix_calllogcrmsync_tenant_inbound_crm_config_id'), table_name='calllogcrmsync')
    op.drop_index(op.f('ix_calllogcrmsync_id'), table_name='calllogcrmsync')
    op.drop_index(op.f('ix_calllogcrmsync_external_item_id'), table_name='calllogcrmsync')
    op.drop_index(op.f('ix_calllogcrmsync_call_log_id'), table_name='calllogcrmsync')
    op.drop_table('calllogcrmsync')
    op.drop_index(op.f('ix_transcriptmessage_user_id'), table_name='transcriptmessage')
    op.drop_index(op.f('ix_transcriptmessage_id'), table_name='transcriptmessage')
    op.drop_index(op.f('ix_transcriptmessage_call_session_id'), table_name='transcriptmessage')
    op.drop_index(op.f('ix_transcriptmessage_agent_id'), table_name='transcriptmessage')
    op.drop_table('transcriptmessage')
    op.drop_index(op.f('ix_slotreservation_tenant_id'), table_name='slotreservation')
    op.drop_index('ix_slotreservation_tenant_active_time', table_name='slotreservation')
    op.drop_index(op.f('ix_slotreservation_status'), table_name='slotreservation')
    op.drop_index(op.f('ix_slotreservation_slot_start'), table_name='slotreservation')
    op.drop_index(op.f('ix_slotreservation_id'), table_name='slotreservation')
    op.drop_index(op.f('ix_slotreservation_call_session_id'), table_name='slotreservation')
    op.drop_index(op.f('ix_slotreservation_agent_id'), table_name='slotreservation')
    op.drop_table('slotreservation')
    op.drop_index(op.f('ix_resumeinterview_twilio_call_sid'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_tenant_id'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_status'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_resume_id'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_job_description_id'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_id'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_crm_item_id'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_crm_batch_id'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_call_session_id'), table_name='resumeinterview')
    op.drop_index(op.f('ix_resumeinterview_agent_id'), table_name='resumeinterview')
    op.drop_table('resumeinterview')
    op.drop_index(op.f('ix_knowledgebasechunk_vector_id'), table_name='knowledgebasechunk')
    op.drop_index(op.f('ix_knowledgebasechunk_id'), table_name='knowledgebasechunk')
    op.drop_index(op.f('ix_knowledgebasechunk_document_id'), table_name='knowledgebasechunk')
    op.drop_index(op.f('ix_knowledgebasechunk_chunk_index'), table_name='knowledgebasechunk')
    op.drop_table('knowledgebasechunk')
    op.drop_index(op.f('ix_calllog_tenant_id'), table_name='calllog')
    op.drop_index(op.f('ix_calllog_id'), table_name='calllog')
    op.drop_index(op.f('ix_calllog_external_call_id'), table_name='calllog')
    op.drop_index(op.f('ix_calllog_call_session_id'), table_name='calllog')
    op.drop_index(op.f('ix_calllog_call_id'), table_name='calllog')
    op.drop_table('calllog')
    op.drop_index('uq_appointment_tenant_slot_active', table_name='appointment', postgresql_where=sa.text("status != 'cancelled'"), sqlite_where=sa.text("status != 'cancelled'"))
    op.drop_index(op.f('ix_appointment_tenant_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_slot_start'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_agent_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_usagerecord_id'), table_name='usagerecord')
    op.drop_table('usagerecord')
    op.drop_index(op.f('ix_resume_upload_mode'), table_name='resume')
    op.drop_index(op.f('ix_resume_tenant_id'), table_name='resume')
    op.drop_index(op.f('ix_resume_status'), table_name='resume')
    op.drop_index(op.f('ix_resume_job_description_id'), table_name='resume')
    op.drop_index(op.f('ix_resume_id'), table_name='resume')
    op.drop_index(op.f('ix_resume_candidate_status'), table_name='resume')
    op.drop_index(op.f('ix_resume_batch_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_phonenumber_twilio_phone_number_sid'), table_name='phonenumber')
    op.drop_index(op.f('ix_phonenumber_tenant_id'), table_name='phonenumber')
    op.drop_index(op.f('ix_phonenumber_phone_number'), table_name='phonenumber')
    op.drop_index(op.f('ix_phonenumber_id'), table_name='phonenumber')
    op.drop_table('phonenumber')
    op.drop_index(op.f('ix_knowledgebasedocument_tenant_id'), table_name='knowledgebasedocument')
    op.drop_index(op.f('ix_knowledgebasedocument_id'), table_name='knowledgebasedocument')
    op.drop_index(op.f('ix_knowledgebasedocument_agent_id'), table_name='knowledgebasedocument')
    op.drop_table('knowledgebasedocument')
    op.drop_index(op.f('ix_callsession_twilio_call_sid'), table_name='callsession')
    op.drop_index(op.f('ix_callsession_id'), table_name='callsession')
    op.drop_table('callsession')
    op.drop_table('user_tenant_association')
    op.drop_index(op.f('ix_tenantinboundcrmconfig_tenant_id'), table_name='tenantinboundcrmconfig')
    op.drop_index(op.f('ix_tenantinboundcrmconfig_id'), table_name='tenantinboundcrmconfig')
    op.drop_index(op.f('ix_tenantinboundcrmconfig_container_id'), table_name='tenantinboundcrmconfig')
    op.drop_table('tenantinboundcrmconfig')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_stripe_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_stripe_session_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_stripe_customer_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_crm_type'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_token'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_expires_at'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    op.drop_index(op.f('ix_passwordresettoken_user_id'), table_name='passwordresettoken')
    op.drop_index(op.f('ix_passwordresettoken_token'), table_name='passwordresettoken')
    op.drop_index(op.f('ix_passwordresettoken_id'), table_name='passwordresettoken')
    op.drop_index(op.f('ix_passwordresettoken_expires_at'), table_name='passwordresettoken')
    op.drop_table('passwordresettoken')
    op.drop_index(op.f('ix_jobdescription_tenant_id'), table_name='jobdescription')
    op.drop_index(op.f('ix_jobdescription_id'), table_name='jobdescription')
    op.drop_table('jobdescription')
    op.drop_index(op.f('ix_invite_token'), table_name='invite')
    op.drop_index(op.f('ix_invite_id'), table_name='invite')
    op.drop_index(op.f('ix_invite_email'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_crmconfig_id'), table_name='crmconfig')
    op.drop_index(op.f('ix_crmconfig_crm_type'), table_name='crmconfig')
    op.drop_index(op.f('ix_crmconfig_container_id'), table_name='crmconfig')
    op.drop_table('crmconfig')
    op.drop_index('uq_agent_single_inbound_per_tenant', table_name='agent', postgresql_where=sa.text('is_inbound_agent = true AND is_deleted = false'))
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_user_provider_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_provider'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ttsvoice_provider_id'), table_name='ttsvoice')
    op.drop_index(op.f('ix_ttsvoice_language_code'), table_name='ttsvoice')
    op.drop_index(op.f('ix_ttsvoice_is_active'), table_name='ttsvoice')
    op.drop_index(op.f('ix_ttsvoice_id'), table_name='ttsvoice')
    op.drop_table('ttsvoice')
    op.drop_index(op.f('ix_model_id'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_businesshours_tenant_id'), table_name='businesshours')
    op.drop_index(op.f('ix_businesshours_id'), table_name='businesshours')
    op.drop_table('businesshours')
    op.drop_index(op.f('ix_blockedslot_tenant_id'), table_name='blockedslot')
    op.drop_index(op.f('ix_blockedslot_id'), table_name='blockedslot')
    op.drop_table('blockedslot')
    op.drop_index(op.f('ix_ttsprovider_slug'), table_name='ttsprovider')
    op.drop_index(op.f('ix_ttsprovider_id'), table_name='ttsprovider')
    op.drop_table('ttsprovider')
    op.drop_index(op.f('ix_tenant_stripe_subscription_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_stripe_customer_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_provider_name'), table_name='provider')
    op.drop_index(op.f('ix_provider_id'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_plan_name'), table_name='plan')
    op.drop_index(op.f('ix_plan_id'), table_name='plan')
    op.drop_index(op.f('ix_plan_crm_type'), table_name='plan')
    op.drop_table('plan')
    # ### end Alembic commands ###
