"""onprem_baseline_full_schema

New root of the migration graph. The original root (a3a08e39e50b) assumed a
pre-existing schema that was bootstrapped outside of Alembic entirely (this
project's earliest tables — user, tenant, role, agent, callsession,
phonenumber, etc. — were never created by any committed migration). That
silently never mattered because no environment ever ran `alembic upgrade
head` against a truly empty database — every real deployment inherited an
already-populated schema. On-premise customers start exactly there.

This migration creates only the tables that no other migration in the chain
ever creates (verified by scanning every op.create_table()/op.rename_table()
call in alembic/versions/) — everything else is still created/altered by the
original 78-migration chain, unchanged, so all the raw-SQL DDL in that chain
(pgcrypto/pgvector extensions, the audit-log append-only RULE/trigger, RLS,
etc.) still runs exactly as before. `phonenumber` is deliberately created in
its pre-global-uniqueness form so a3a08e39e50b's DROP CONSTRAINT still
applies correctly immediately after this migration.

Revision ID: f2ab218de84d
Revises: (none — new root; a3a08e39e50b now depends on this instead)
Create Date: 2026-06-23 18:44:52.900732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2ab218de84d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Several revision IDs later in this chain are long, descriptive,
    # date-prefixed slugs (e.g. "20260415_add_tts_provider_and_voice", 34
    # chars) that exceed Alembic's default alembic_version.version_num
    # VARCHAR(32). Widen it up front so `alembic upgrade head` doesn't fail
    # with StringDataRightTruncation partway through a fresh install. (The
    # real Neon DB never hit this because its alembic_version was presumably
    # widened manually out-of-band at some point — not captured in any
    # migration here.)
    op.execute("ALTER TABLE alembic_version ALTER COLUMN version_num TYPE VARCHAR(255)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('crm_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_crm_type'), 'plan', ['crm_type'], unique=False)
    op.create_index(op.f('ix_plan_id'), 'plan', ['id'], unique=False)
    op.create_index(op.f('ix_plan_name'), 'plan', ['name'], unique=True)
    op.create_table('provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.create_index(op.f('ix_provider_name'), 'provider', ['name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('credits', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tenant_stripe_customer_id'), 'tenant', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_tenant_stripe_subscription_id'), 'tenant', ['stripe_subscription_id'], unique=False)
    # uq_tenant_name_active (WHERE deleted_at IS NULL) omitted: deleted_at
    # doesn't exist yet — 20260518_tenant_name_unique_active.py creates it
    # after 20260518_add_tenant_deleted_at.py adds the column.
    op.create_table('ttsprovider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('supports_ssml', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ttsprovider_id'), 'ttsprovider', ['id'], unique=False)
    # unique=True is required here (not just dedup) — early seed-data inserts
    # use `ON CONFLICT (slug) DO NOTHING`, which needs the unique constraint
    # to exist immediately, not just once 7d1c547d8a1f_add_missing_agent_columns.py
    # (which redundantly recreates this same index) runs later in the chain.
    op.create_index(op.f('ix_ttsprovider_slug'), 'ttsprovider', ['slug'], unique=True)
    op.create_table('model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.String(length=1000), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.Column('llm_cost_per_minute', sa.Float(), nullable=True),
    sa.Column('twilio_cost_per_minute', sa.Float(), nullable=True),
    sa.Column('total_cost_per_minute', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_table('ttsvoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('external_voice_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('accent', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preview_audio_url', sa.String(length=1000), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ttsprovider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_voice_id', name='uq_ttsvoice_provider_external')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('join_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('provider_profile', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_provider'), 'user', ['provider'], unique=False)
    op.create_index(op.f('ix_user_provider_user_id'), 'user', ['provider_user_id'], unique=False)
    # uq_user_email_active (WHERE deleted_at IS NULL) omitted: deleted_at
    # doesn't exist yet — 20260618_user_email_partial_unique.py creates it
    # once the column exists.
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('voice_type', sa.String(length=100), nullable=True),
    sa.Column('fallback_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('provider_agent_id', sa.String(length=255), nullable=True),
    sa.Column('tts_provider_id', sa.UUID(), nullable=True),
    sa.Column('tts_voice_id', sa.UUID(), nullable=True),
    sa.Column('tts_settings_json', sa.JSON(), nullable=True),
    sa.Column('agent_temperature', sa.Integer(), nullable=True),
    sa.Column('agent_max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    # is_inbound_agent and is_follow_up_agent omitted: added non-idempotently
    # by b6d5f9e0d2aa_add_inbound_agent_flag.py and
    # 20260505_agent_follow_up_and_appointment_crm.py respectively (plain
    # op.add_column, no existence guard) — including them here would make
    # those ADD COLUMN statements fail with "column already exists".
    # stt_provider_id, stt_model_id (-> sttmodel/sttprovider) and
    # transfer_route_id (-> transferroute) deliberately omitted: those tables
    # don't exist yet at this point in the chain. The real migrations that
    # introduce them (20260608_add_stt_catalog_and_agent_stt_columns.py,
    # 20260504_transferroute_and_agent_fk.py) are idempotent (guarded by
    # column-existence checks) and add these columns + FKs back once their
    # target tables exist.
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tts_provider_id'], ['ttsprovider.id'], ),
    sa.ForeignKeyConstraint(['tts_voice_id'], ['ttsvoice.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_table('crmconfig',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crm_type', sa.String(length=20), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=1000), nullable=False),
    sa.Column('container_id', sa.String(length=200), nullable=True),
    sa.Column('container_url', sa.String(length=500), nullable=True),
    sa.Column('additional_config', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crmconfig_container_id'), 'crmconfig', ['container_id'], unique=False)
    op.create_index(op.f('ix_crmconfig_crm_type'), 'crmconfig', ['crm_type'], unique=True)
    op.create_index(op.f('ix_crmconfig_id'), 'crmconfig', ['id'], unique=False)
    op.create_table('invite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_email'), 'invite', ['email'], unique=False)
    # ix_invite_email_tenant_id omitted: created non-idempotently by
    # 20260521_schema_v1_gaps.py later in the chain.
    op.create_index(op.f('ix_invite_id'), 'invite', ['id'], unique=False)
    op.create_index(op.f('ix_invite_token'), 'invite', ['token'], unique=True)
    op.create_table('jobdescription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('years_experience_min', sa.Integer(), nullable=True),
    sa.Column('years_experience_max', sa.Integer(), nullable=True),
    sa.Column('education_requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=12), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('key_responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pass_match_threshold', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_weight_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matching_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobdescription_tenant_id'), 'jobdescription', ['tenant_id'], unique=False)
    op.create_table('passwordresettoken',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresettoken_expires_at'), 'passwordresettoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_passwordresettoken_id'), 'passwordresettoken', ['id'], unique=False)
    op.create_index(op.f('ix_passwordresettoken_token'), 'passwordresettoken', ['token'], unique=True)
    op.create_index(op.f('ix_passwordresettoken_user_id'), 'passwordresettoken', ['user_id'], unique=False)
    op.create_table('refreshtoken',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('replaced_by_token', sa.String(length=255), nullable=True),
    sa.Column('replaced_access_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_expires_at'), 'refreshtoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refreshtoken_id'), 'refreshtoken', ['id'], unique=False)
    op.create_index(op.f('ix_refreshtoken_token'), 'refreshtoken', ['token'], unique=True)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('crm_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'crm_type', name='uq_user_crm_subscription')
    )
    op.create_index(op.f('ix_subscription_crm_type'), 'subscription', ['crm_type'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_customer_id'), 'subscription', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_session_id'), 'subscription', ['stripe_session_id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_subscription_id'), 'subscription', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('user_tenant_association',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    # product_id omitted: product table doesn't exist yet at this point.
    # 20260429_add_products_and_user_link.py adds it back (idempotent).
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # knowledgebase/kbfile/kbchunk: per 20260611_cleanup_orphan_tables.py's own
    # docstring, the rename migration that's supposed to produce these
    # ("20260611_rename_tables_base_class") "was stamped as applied without
    # executing" in every real deployment — the new-named tables were created
    # directly by a later autogenerate run instead, and the old-named
    # (knowledge_bases/kb_files/kb_chunks) tables that rename would have
    # operated on were never created either. Created directly under final
    # names here, matching every real deployment's actual history; the
    # rename migration is patched to skip these three (see that file).
    # embedding stays Text here (not vector) — 20260611_kb_pgvector.py casts
    # it to vector(1536) immediately after.
    op.create_table('knowledgebase',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebase_id'), 'knowledgebase', ['id'], unique=False)
    op.create_index(op.f('ix_knowledgebase_workspace_id'), 'knowledgebase', ['workspace_id'], unique=False)
    op.create_table('kbfile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('gcs_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledgebase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kbfile_id'), 'kbfile', ['id'], unique=False)
    op.create_index(op.f('ix_kbfile_kb_id'), 'kbfile', ['kb_id'], unique=False)
    op.create_table('kbchunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['kbfile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledgebase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kbchunk_file_id'), 'kbchunk', ['file_id'], unique=False)
    op.create_index(op.f('ix_kbchunk_id'), 'kbchunk', ['id'], unique=False)
    op.create_index(op.f('ix_kbchunk_kb_id'), 'kbchunk', ['kb_id'], unique=False)
    op.create_table('phonenumber',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('twilio_phone_number_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_account_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_auth_token', sa.String(length=500), nullable=True),
    sa.Column('assistant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # Original (pre-global-uniqueness) constraint — migration a3a08e39e50b
    # converts this to uq_phone_number_global immediately after this baseline.
    sa.UniqueConstraint('tenant_id', 'phone_number', name='uq_phone_number_per_tenant')
    )
    op.create_index(op.f('ix_phonenumber_id'), 'phonenumber', ['id'], unique=False)
    op.create_index(op.f('ix_phonenumber_phone_number'), 'phonenumber', ['phone_number'], unique=False)
    op.create_index(op.f('ix_phonenumber_tenant_id'), 'phonenumber', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_phonenumber_twilio_phone_number_sid'), 'phonenumber', ['twilio_phone_number_sid'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='parsestatus'), nullable=False),
    sa.Column('upload_mode', sa.Enum('SINGLE', 'BATCH', name='uploadmode'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('overall_match_score', sa.Float(), nullable=True),
    sa.Column('match_percent', sa.Integer(), nullable=True),
    sa.Column('fit_label', sa.String(length=32), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('candidate_status', sa.Enum('QUALIFIED', 'PARTIALLY_QUALIFIED', 'REJECTED', name='candidatestatus'), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('parse_source', sa.String(length=32), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['jobdescription.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_batch_id'), 'resume', ['batch_id'], unique=False)
    op.create_index(op.f('ix_resume_candidate_status'), 'resume', ['candidate_status'], unique=False)
    op.create_index(op.f('ix_resume_id'), 'resume', ['id'], unique=False)
    op.create_index(op.f('ix_resume_job_description_id'), 'resume', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resume_status'), 'resume', ['status'], unique=False)
    op.create_index(op.f('ix_resume_tenant_id'), 'resume', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_resume_upload_mode'), 'resume', ['upload_mode'], unique=False)
    op.create_table('callsession',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.String(length=20), server_default='inbound', nullable=False),
    sa.Column('success_evaluation', sa.String(length=20), nullable=True),
    sa.Column('ended_reason', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('cost_currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('call_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=255), nullable=True),
    sa.Column('from_number', sa.String(length=50), nullable=True),
    sa.Column('to_number', sa.String(length=50), nullable=True),
    sa.Column('assistant_phone_number', sa.String(length=50), nullable=True),
    sa.Column('customer_phone_number', sa.String(length=50), nullable=True),
    sa.Column('call_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transferred', sa.Boolean(), server_default='false', nullable=False),
    # call_flow_id omitted: callflow table doesn't exist yet at this point.
    # 20260529_add_call_flows_and_folders.py adds it back (idempotent).
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callsession_id'), 'callsession', ['id'], unique=False)
    op.create_index(op.f('ix_callsession_twilio_call_sid'), 'callsession', ['twilio_call_sid'], unique=False)
    op.create_table('calllog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=False),
    sa.Column('external_call_id', sa.String(length=255), nullable=True),
    sa.Column('call_type', sa.String(length=20), server_default='inbound', nullable=False),
    sa.Column('success_evaluation', sa.String(length=20), nullable=True),
    sa.Column('ended_reason', sa.String(length=255), nullable=True),
    sa.Column('transferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assistant_phone_number', sa.String(length=50), nullable=True),
    sa.Column('customer_phone_number', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('cost_currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('call_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calllog_call_id'), 'calllog', ['call_id'], unique=False)
    op.create_index(op.f('ix_calllog_call_session_id'), 'calllog', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_calllog_external_call_id'), 'calllog', ['external_call_id'], unique=False)
    op.create_index(op.f('ix_calllog_id'), 'calllog', ['id'], unique=False)
    op.create_index(op.f('ix_calllog_tenant_id'), 'calllog', ['tenant_id'], unique=False)
    op.create_table('resumeinterview',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=True),
    sa.Column('candidate_phone', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), server_default='SCHEDULE_REQUESTED', nullable=False),
    sa.Column('crm_type', sa.String(length=20), nullable=True),
    sa.Column('crm_item_id', sa.String(length=128), nullable=True),
    sa.Column('crm_batch_id', sa.String(length=128), nullable=True),
    sa.Column('phone_number_id', sa.UUID(), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_description_id'], ['jobdescription.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phonenumber.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumeinterview_agent_id'), 'resumeinterview', ['agent_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_call_session_id'), 'resumeinterview', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_crm_batch_id'), 'resumeinterview', ['crm_batch_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_crm_item_id'), 'resumeinterview', ['crm_item_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_id'), 'resumeinterview', ['id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_job_description_id'), 'resumeinterview', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_resume_id'), 'resumeinterview', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_status'), 'resumeinterview', ['status'], unique=False)
    op.create_index(op.f('ix_resumeinterview_tenant_id'), 'resumeinterview', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_resumeinterview_twilio_call_sid'), 'resumeinterview', ['twilio_call_sid'], unique=False)
    op.create_table('transcriptmessage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptmessage_agent_id'), 'transcriptmessage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_transcriptmessage_call_session_id'), 'transcriptmessage', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_transcriptmessage_id'), 'transcriptmessage', ['id'], unique=False)
    op.create_index(op.f('ix_transcriptmessage_user_id'), 'transcriptmessage', ['user_id'], unique=False)
    op.create_table('scheduledcall',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_crm_config_id', sa.UUID(), nullable=True),
    sa.Column('crm_container_id', sa.String(length=200), nullable=True),
    sa.Column('crm_container_url', sa.String(length=500), nullable=True),
    sa.Column('crm_type', sa.String(length=20), nullable=True),
    sa.Column('monday_board_id', sa.String(length=50), nullable=True),
    sa.Column('monday_board_url', sa.String(length=500), nullable=True),
    sa.Column('resume_interview_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_interview_id'], ['resumeinterview.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduledcall_crm_container_id'), 'scheduledcall', ['crm_container_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_crm_type'), 'scheduledcall', ['crm_type'], unique=False)
    op.create_index(op.f('ix_scheduledcall_id'), 'scheduledcall', ['id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_monday_board_id'), 'scheduledcall', ['monday_board_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_resume_interview_id'), 'scheduledcall', ['resume_interview_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_tenant_crm_config_id'), 'scheduledcall', ['tenant_crm_config_id'], unique=False)
    op.create_index(op.f('ix_scheduledcall_user_id'), 'scheduledcall', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('kbchunk')
    op.drop_table('kbfile')
    op.drop_table('knowledgebase')
    op.drop_table('scheduledcall')
    op.drop_table('transcriptmessage')
    op.drop_table('resumeinterview')
    op.drop_table('calllog')
    op.drop_table('callsession')
    op.drop_table('resume')
    op.drop_table('phonenumber')
    op.drop_table('user_tenant_association')
    op.drop_table('subscription')
    op.drop_table('refreshtoken')
    op.drop_table('passwordresettoken')
    op.drop_table('jobdescription')
    op.drop_table('invite')
    op.drop_table('crmconfig')
    op.drop_table('agent')
    op.drop_table('user')
    op.drop_table('ttsvoice')
    op.drop_table('model')
    op.drop_table('ttsprovider')
    op.drop_table('tenant')
    op.drop_table('role')
    op.drop_table('provider')
    op.drop_table('plan')
