"""
v2 Active Call Insights endpoints.

Auth: API key + x-workspace-id (get_workspace).

GET  /api/v2/active-calls                       — list all active calls in the workspace
GET  /api/v2/active-calls/{room_name}/insights  — AI insights for a live call (rate-limited 30/min per workspace)

Transcript source: Redis key ``call_transcript:{room_name}`` written by the voice pipeline
on each turn.  Insights are generated by Gemini with response_mime_type='application/json'.
On any Gemini error the endpoint returns a safe neutral fallback — it never raises 5xx.
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.api.deps import get_db, get_workspace
from app.core.logger import logger
from app.core.workspace import Workspace
from app.models.agent import Agent
from app.models.call_session import CallSession
from app.services.gemini_service import gemini_service

router = APIRouter(prefix="/active-calls", tags=["Active Call Insights"])

# ── Pydantic response schemas ──────────────────────────────────────────────────

class ActiveCallItem(BaseModel):
    room_name: str
    call_id: str
    agent_name: str
    duration_seconds: int
    from_number: Optional[str]
    to_number: Optional[str]
    started_at: datetime


class CallInsightsResponse(BaseModel):
    sentiment: str          # 'positive' | 'neutral' | 'negative'
    sentiment_score: float  # 0.0 – 1.0
    topics: List[str]
    summary: str
    suggestions: List[str]
    call_duration_seconds: int


# ── Helpers ───────────────────────────────────────────────────────────────────

_INSIGHTS_PROMPT = (
    "Analyse this call transcript. Return JSON: "
    '{{\"sentiment\": \"positive|neutral|negative\", '
    '"sentiment_score\": <float 0-1>, '
    '"topics\": [<max 5 strings>], '
    '"summary\": \"<max 2 sentences>\", '
    '"suggestions\": [<max 3 action strings>]}}. '
    "Transcript:\n{transcript}"
)

_FALLBACK: dict = {
    "sentiment": "neutral",
    "sentiment_score": 0.5,
    "topics": [],
    "summary": "Analysis unavailable.",
    "suggestions": [],
}


def _room_to_call_session_id(room_name: str) -> uuid.UUID:
    """Parse call_session UUID from room name (format: room_{uuid})."""
    try:
        return uuid.UUID(room_name.removeprefix("room_"))
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid room_name format. Expected room_{uuid}.",
        )


async def _read_redis_transcript(room_name: str) -> list[dict]:
    """Return the turns list from Redis, or [] if unavailable."""
    try:
        from app.utils.redis_client import get_redis
        redis = get_redis()
        if redis is None:
            return []
        raw = await redis.get(f"call_transcript:{room_name}")
        return json.loads(raw) if raw else []
    except Exception as exc:
        logger.debug("Redis transcript read failed: %s", exc)
        return []


def _format_transcript(turns: list[dict]) -> str:
    lines = []
    for t in turns:
        role = "Agent" if t.get("role") == "agent" else "Customer"
        lines.append(f"{role}: {t.get('text', '')}")
    return "\n".join(lines)


async def _enforce_insights_rate_limit(workspace_id: str) -> None:
    """30 req/min sliding window per workspace on the insights endpoint."""
    from app.middleware.rate_limit_middleware import (
        _check_rate_limit,
        build_rate_limit_error,
    )
    allowed, retry_after = await _check_rate_limit(
        f"active_call_insights:{workspace_id}", limit=30, window=60
    )
    if not allowed:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={"error": build_rate_limit_error(retry_after)},
        )


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("", response_model=List[ActiveCallItem])
async def list_active_calls(
    workspace: Workspace = Depends(get_workspace),
    db: Session = Depends(get_db),
) -> List[ActiveCallItem]:
    """Return all currently active call sessions for the authenticated workspace."""
    stmt = (
        select(CallSession, Agent.name.label("agent_name"))
        .join(Agent, CallSession.agent_id == Agent.id, isouter=True)
        .where(
            CallSession.tenant_id == workspace.id,
            CallSession.status == "active",
        )
    )
    rows = db.execute(stmt).all()

    now = datetime.now(timezone.utc)
    result: List[ActiveCallItem] = []
    for row in rows:
        session: CallSession = row[0]
        agent_name: str = row[1] or "Unknown Agent"

        started_at = session.start_time
        if started_at is not None and started_at.tzinfo is None:
            started_at = started_at.replace(tzinfo=timezone.utc)

        duration = int((now - started_at).total_seconds()) if started_at else 0

        result.append(
            ActiveCallItem(
                room_name=f"room_{session.id}",
                call_id=str(session.id),
                agent_name=agent_name,
                duration_seconds=max(0, duration),
                from_number=session.from_number,
                to_number=session.to_number,
                started_at=started_at or now,
            )
        )
    return result


@router.get("/{room_name}/insights", response_model=CallInsightsResponse)
async def get_call_insights(
    room_name: str,
    request: Request,
    workspace: Workspace = Depends(get_workspace),
    db: Session = Depends(get_db),
) -> CallInsightsResponse:
    """
    Return AI-generated insights for an active call.

    Rate-limited to 30 req/min per workspace.
    Returns a safe neutral fallback on Gemini error — never raises 5xx.
    """
    await _enforce_insights_rate_limit(str(workspace.id))

    # Workspace isolation: verify this room belongs to the caller's workspace.
    call_session_id = _room_to_call_session_id(room_name)
    session: Optional[CallSession] = db.get(CallSession, call_session_id)
    if session is None or session.tenant_id != workspace.id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Room not found or does not belong to this workspace.",
        )

    # Derive call duration
    now = datetime.now(timezone.utc)
    started_at = session.start_time
    if started_at is not None and started_at.tzinfo is None:
        started_at = started_at.replace(tzinfo=timezone.utc)
    call_duration_seconds = int((now - started_at).total_seconds()) if started_at else 0

    # Read live transcript from Redis
    turns = await _read_redis_transcript(room_name)
    if not turns:
        return CallInsightsResponse(
            **_FALLBACK,
            call_duration_seconds=max(0, call_duration_seconds),
        )

    transcript_text = _format_transcript(turns)
    prompt = _INSIGHTS_PROMPT.format(transcript=transcript_text)

    # Call Gemini with JSON mode; graceful fallback on any error
    try:
        raw = gemini_service.generate_json(prompt=prompt)

        sentiment = str(raw.get("sentiment", "neutral")).lower()
        if sentiment not in ("positive", "neutral", "negative"):
            sentiment = "neutral"

        score = float(raw.get("sentiment_score", 0.5))
        score = max(0.0, min(1.0, score))

        topics = [str(t) for t in raw.get("topics", [])[:5]]
        summary = str(raw.get("summary", "Analysis unavailable."))
        suggestions = [str(s) for s in raw.get("suggestions", [])[:3]]

        return CallInsightsResponse(
            sentiment=sentiment,
            sentiment_score=round(score, 4),
            topics=topics,
            summary=summary,
            suggestions=suggestions,
            call_duration_seconds=max(0, call_duration_seconds),
        )

    except Exception as exc:
        logger.warning(
            "Gemini insights failed for room=%s (%s) — returning fallback",
            room_name,
            exc,
        )
        return CallInsightsResponse(
            **_FALLBACK,
            call_duration_seconds=max(0, call_duration_seconds),
        )
